# This is a basic workflow to help you get started with Actions
# Name of workflow
name: myWorkflow

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: 
      - "**"
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
concurrency:  
  #group: ${{ github.workflow }}-${{ github.ref }}
  #group: ${{ github.head_ref || github.run_id }}
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true
  
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  hellojob:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: myCheckoutStep
        uses: actions/checkout@v3
      # Runs a single command using the runners shell
      - name: myHelloWorldStep
        run: echo "Hello, world!"
        shell: bash
      # Runs a set of commands using the runners shell
      - name: myMulti-lineScriptStep
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
  goodbyejob:
    runs-on: ubuntu-latest
    steps:
      - name: myHelloWorldStep
        run: sleep 50
        shell: bash
